defaults:
  - algorithm: mappo
  - environment: pettingzoo_mw
  
  - logger: wandb
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: submitit_local
  - _self_

hydra:
  searchpath:
    - file://src/configs/
