defaults:
  - algorithm: mappo
  - environment: pettingzoo_mw
  
  - logger: wandb
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: submitit_local
  - _self_
name: hi

algorithm:
  device:
    cuda: False
    cuda_deterministic: False
hydra:
  searchpath:
    - file://src/configs/
  launcher:
    timeout_min: 6000
    gpus_per_node: 0

    