defaults:
  - original/maddpg@_here_
  - _self_

train:
  # number of parallel environments for training data collection
  n_rollout_threads: 20
  eval_interval: 5000

name: maddpg
algo:
  share_param: True